# configs/config.yaml

# API密钥和认证信息
api_keys:
  llm: "sk-aeb0ed24d0c045e78d73fff879da5f07" # 你的LLM API密钥

# 文件和目录路径
paths:
  input_file: "data/input/astroEntity.xlsx"
  output_dir: "data/output"
  vector_db_path: "data/vectordb" # ChromaDB数据存储路径

# 模型配置
llm:
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1" # LLM API的URL
  extraction_model: "deepseek-v3" # 用于关系抽取的模型
  judge_model: "deepseek-v3"      # 用于规范化判断的模型

embedding:
  api_url: "http://210.40.16.12:45389" # 嵌入模型服务的URL

# 向量数据库配置
vector_db:
  similarity_threshold: 0.1 # 用于筛选候选者的相似度阈值
  top_k: 5                   # 检索最相似的候选者数量

# 管道运行配置
pipeline:
  num_workers: 4 # 并行处理实体的线程数

#minerU配置
minerU:
    api_url: "http://210.40.16.12:42181/file_parse"

#文本切块大小配置
chunk:
  chunk_size: 1024
  chunk_overlap: 30